name: mima-tools
version: 0.1.0.0
license: MIT
author: Garmelon <joscha@plugh.de>
copyright: 2019-2020 Garmelon

synopsis: Tools for the MiMa (MinimalMaschine)
description: Please see the README on GitHub at <https://github.com/Garmelon/mima-tools#readme>
github: Garmelon/mima-tools

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - OddWord >= 1.0 && < 1.1
  - aeson
  - aeson-pretty
  - binary
  - bytestring
  - containers
  - text
  - transformers
  - unordered-containers

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - QuickCheck
      - hspec
      - mima-tools
