name:                mima-tools
version:             0.1.0.0
github:              "Garmelon/mima-tools"
license:             MIT
author:              "Garmelon"
maintainer:          "joscha@plugh.de"
copyright:           "2019 Garmelon"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Garmelon/mima-tools#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- binary
- bytestring
- containers
- optparse-applicative
- text
- OddWord >= 1.0 && < 1.1

library:
  source-dirs: src

executables:
  mima-run:
    main: MimaRun.hs
    source-dirs: app
    ghc-options:
    - -main-is MimaRun
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mima-tools

tests:
  mima-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mima-tools
